### PR TITLE
Update nvidia-device-plugin.yml

### PR DESCRIPTION
**Pull request by frankenstien-831**
can i ask for a help?

### CODE REVIEW

**Comment by elgalu** [comment]
Why is this open for 2 years? why is it switching the docker image to a different registry?

**Comment by elezar** [comment]
Hi @elgalu. The GitHub repo is a "read-only" mirror to our GitLab repository (https://gitlab.com/nvidia/kubernetes/device-plugin) where we do our development. We usually have an "answer app" that auto-responds to PRs to inform the creators that this is the case.

@frankenstien-831 could you give more context on your PR -- ideally as an issue, or create a merge request to the GitLab repo mentioned above.

**Comment by frankenstien-831** [comment]
I’m not sure, am I able to do it..2 years back was a lot of updated files version 

Louis Lee

© 2021. All Rights Reserved 
The information contained in this e-mail message is confidential - please do not cross-post. This communication is intended for the use of the addressee(s) only. If you are not the intended recipient, you are hereby notified that any review, reliance, disclosure, distribution or copying of this communication may be prohibited by law and might constitute a breach of confidence. If you have received this communication in error, please notify us immediately and delete it and all copies (including attachments) from your system.

On 10 Nov 2021, at 17:30, Evan Lezar ***@***.***> wrote:

﻿
Hi @elgalu. The GitHub repo is a "read-only" mirror to our GitLab repository (https://gitlab.com/nvidia/kubernetes/device-plugin) where we do our development. We usually have an "answer app" that auto-responds to PRs to inform the creators that this is the case.

@frankenstien-831 could you give more context on your PR -- ideally as an issue, or create a merge request to the GitLab repo mentioned above.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by elezar** [comment]
I am closing this PR. It is out of date. If there changes are still required please open a Merge Request against https://gitlab.com/nvidia/kubernetes/device-plugin

**Pull request closed without merging**
