### PR TITLE
Switch to Ubuntu22.04 image

### PR DESCRIPTION
**Pull request by elezar**
This change switches to an ubuntu22.04 image by default to ensure a more up to date glibc version. This is required when using nvgpu drivers for iGPU devices.

For older base image versions the following is shown in the contianer:
```
ldd /usr/lib/aarch64-linux-gnu/nvidia/libcuda.so.1
ldd: warning: you do not have execution permission for `/usr/lib/aarch64-linux-gnu/nvidia/libcuda.so.1'
/usr/lib/aarch64-linux-gnu/nvidia/libcuda.so.1: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/aarch64-linux-gnu/nvidia/libnvrm_gpu.so)
/usr/lib/aarch64-linux-gnu/nvidia/libcuda.so.1: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib/aarch64-linux-gnu/nvidia/libnvos.so)
/usr/lib/aarch64-linux-gnu/nvidia/libcuda.so.1: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/aarch64-linux-gnu/nvidia/libnvos.so)
/usr/lib/aarch64-linux-gnu/nvidia/libcuda.so.1: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/aarch64-linux-gnu/nvidia/libnvrm_sync.so)
/usr/lib/aarch64-linux-gnu/nvidia/libcuda.so.1: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib/aarch64-linux-gnu/nvidia/libnvsciipc.so)
/usr/lib/aarch64-linux-gnu/nvidia/libcuda.so.1: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/aarch64-linux-gnu/nvidia/libnvsciipc.so)
	linux-vdso.so.1 (0x0000ffffa7c69000)
	libm.so.6 => /lib64/libm.so.6 (0x0000ffffa5eb0000)
	libc.so.6 => /lib64/libc.so.6 (0x0000ffffa5d3a000)
	/lib/ld-linux-aarch64.so.1 (0x0000ffffa7c2b000)
	libdl.so.2 => /lib64/libdl.so.2 (0x0000ffffa5d19000)
	librt.so.1 => /lib64/librt.so.1 (0x0000ffffa5cf8000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000ffffa5cc3000)
	libnvrm_gpu.so => /usr/lib/aarch64-linux-gnu/nvidia/libnvrm_gpu.so (0x0000ffffa5c51000)
	libnvrm_mem.so => /usr/lib/aarch64-linux-gnu/nvidia/libnvrm_mem.so (0x0000ffffa5c38000)
	libnvos.so => /usr/lib/aarch64-linux-gnu/nvidia/libnvos.so (0x0000ffffa5c16000)
	libnvsocsys.so => /usr/lib/aarch64-linux-gnu/nvidia/libnvsocsys.so (0x0000ffffa5c02000)
	libnvtegrahv.so => /usr/lib/aarch64-linux-gnu/nvidia/libnvtegrahv.so (0x0000ffffa5bef000)
	libnvrm_sync.so => /usr/lib/aarch64-linux-gnu/nvidia/libnvrm_sync.so (0x0000ffffa5bd8000)
	libnvsciipc.so => /usr/lib/aarch64-linux-gnu/nvidia/libnvsciipc.so (0x0000ffffa5ba5000)
	libnvrm_chip.so => /usr/lib/aarch64-linux-gnu/nvidia/libnvrm_chip.so (0x0000ffffa5b91000)
	libnvrm_host1x.so => /usr/lib/aarch64-linux-gnu/nvidia/libnvrm_host1x.so (0x0000ffffa5b6e000)
```

### CODE REVIEW

**Review by tariq1890 — APPROVED** [review]

**Comment by elezar** [comment]
@cdesiniotis do you foresee any issues with this change in the operator?

**Comment by cdesiniotis** [comment]
> @cdesiniotis do you foresee any issues with this change in the operator?

As long as this image, now based on Ubuntu 22.04, works on an Ubuntu 20.04 host, then I have no concerns.
Since we build the Go binaries in the same CUDA base image we use at runtime, I am assuming there should be no GLIBC compatibility issues, correct?

**Comment by cdesiniotis** [comment]
I was able to run the `ubuntu22.04` image just fine on a Ubuntu 20.04 host.

**Review by cdesiniotis — APPROVED** [review]

**Comment by elezar** [comment]
The binaries of the device plugin ONLY run in a container, so there is no issue with mismatches glibc versions there.

**Pull request merged**
