### PR TITLE
report index as RegisteredDevices when device-id-strategy set to index

### PR DESCRIPTION
**Pull request by borgerli**
fix issue https://github.com/NVIDIA/k8s-device-plugin/issues/373

### CODE REVIEW

**Comment by borgerli** [comment]
With this PR, when `device-id-strategy` set to `index`, indexes, instead of UUIDs will be reported to kubelet and informations in checkpoint file looks likes this `"RegisteredDevices":{"nvidia.com/gpu":["0","1"]}`.

**Comment by borgerli** [comment]
@klueska, could you plelase take a look? Thanks.

**Comment by klueska** [comment]
Could you please open an MR against https://gitlab.com/nvidia/kubernetes/device-plugin. This is a read-only mirror.

**Comment by borgerli** [comment]
MR on gitlab:https://gitlab.com/nvidia/kubernetes/device-plugin/-/merge_requests/259

**Pull request closed without merging**
