### PR TITLE
Adding shared GPU support by replicating GPUs.

### LINKED ISSUE #169: Support sharing GPUs
It would be useful to allow containers/pods to share GPUs (similar to a shared workstation) when desired.
---

I have a fork of this device plugin that implements the above functionality.  One has to label nodes as either exclusive access or shared access to the GPUs.  For shared access you must specify the number of replicas of the GPUs to create.  For example, if you have 4 physical GPUs on a node and want to allow each GPU to be allocated twice, one would set the replicas to 2 so there are effectively 8 GPUs for k8s to schedule.

Is this something that would be of interest to this project as a pull request?

### PR DESCRIPTION
**Pull request by ktarplee**
Adding shared GPU support by replicating GPUs.  Closes #169 

This also supports renaming GPUs.

This was pulled from the ACT3 internal repository and has gone through the public release process with the U.S. Air Force.

### CODE REVIEW

**Comment by ktarplee** [comment]
@klueska I signed the commit with my GPG key but I do not know how to make the merge request to the gitlab repo.  Is it true that NVIDIA has it only accepting patches via email?

**Comment by theduke** [comment]
@ktarplee 

> I do not know how to make the merge request to the gitlab repo

Sign up on Gitlab, fork the repo and open a merge request, just like on Github.

Would love to see this merged, testing right now.

**Comment by theduke** [comment]
Just some feedback: tested this on Kubernetes `v1.20.5` and it is working well.

**Comment by ktarplee** [comment]
I forked it on gitlab and was able to make the [MR](https://gitlab.com/nvidia/kubernetes/device-plugin/-/merge_requests/86) against the gitlab repo.  I fixed the one lint error and merged in master so the build is all green now for the MR.

Should we close this pull request since we now have the upstream merge request?

**Comment by klueska** [comment]
Hi Kyle,  Yes, I see the MR on gitlab. I will close this one now. Thanks.

**Pull request closed without merging**
